theme: jekyll-theme-slate
title: Bayesian Statistics Workshop 
description: If you are interested to join the Bayesian Statistics workshop, please set your name on the [participant list](https://docs.google.com/spreadsheets/d/1NRv5ooTUe2hWET-RhIM-XsIZZA5krZmdAJsG0k_O4BE/edit#gid=0)
