theme: jekyll-theme-minimal
title: Bayesian Statistics with R 
description: Material and Code for the Workshop "Advanced methods: Bayesian statistics with R" at the University of Postdam, 2018
show_downloads: true
